language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*@dev


before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
